[build]
builder = "railpack"
buildCommand = "yarn build"
watchPatterns = ["yarn.lock", "apps/notifications-service/**", "packages/**"]

[deploy]
preDeployCommand = "cd apps/notifications-service && yarn db:migrate"
startCommand = "cd apps/notifications-service && yarn start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.multiRegionConfig]
us-west2 = { numReplicas = 1 }
