[build]
builder = "railpack"
buildCommand = "yarn build"
watchPatterns = ["apps/swap-service/**", "packages/**"]

[deploy]
preDeployCommand = "cd apps/swap-service && yarn db:migrate"
startCommand = "cd apps/swap-service && yarn start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.multiRegionConfig]
us-west2 = { numReplicas = 1 }
