[build]
builder = "railpack"
buildCommand = "yarn build"
watchPatterns = ["apps/user-service/**", "packages/**"]

[deploy]
preDeployCommand = "cd apps/user-service && ./node_modules/.bin/prisma migrate deploy"
startCommand = "cd apps/user-service && yarn start:prod"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.multiRegionConfig]
us-west2 = { numReplicas = 1 }
